codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "tests/**"
  - "mocks/**"
  - "proto/**"
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/*.pb.go"
  - "**/*_vtproto.pb.go"

comment:
  layout: "reach, diff, flags, components, files"
  behavior: default
  require_changes: false

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto

  individual_components:
    - component_id: server
      name: Server
      paths:
        - server/**

    - component_id: client
      name: Client
      paths:
        - woodpecker/**

    - component_id: meta
      name: Meta
      paths:
        - meta/**

    - component_id: common
      name: Common
      paths:
        - common/**
