// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_minio_client

import (
	context "context"
	io "io"

	minio "github.com/minio/minio-go/v7"

	mock "github.com/stretchr/testify/mock"
)

// MinioClientAPI is an autogenerated mock type for the MinioClientAPI type
type MinioClientAPI struct {
	mock.Mock
}

type MinioClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MinioClientAPI) EXPECT() *MinioClientAPI_Expecter {
	return &MinioClientAPI_Expecter{mock: &_m.Mock}
}

// CopyObject provides a mock function with given fields: ctx, dst, src
func (_m *MinioClientAPI) CopyObject(ctx context.Context, dst minio.CopyDestOptions, src minio.CopySrcOptions) (minio.UploadInfo, error) {
	ret := _m.Called(ctx, dst, src)

	if len(ret) == 0 {
		panic("no return value specified for CopyObject")
	}

	var r0 minio.UploadInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, minio.CopyDestOptions, minio.CopySrcOptions) (minio.UploadInfo, error)); ok {
		return rf(ctx, dst, src)
	}
	if rf, ok := ret.Get(0).(func(context.Context, minio.CopyDestOptions, minio.CopySrcOptions) minio.UploadInfo); ok {
		r0 = rf(ctx, dst, src)
	} else {
		r0 = ret.Get(0).(minio.UploadInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, minio.CopyDestOptions, minio.CopySrcOptions) error); ok {
		r1 = rf(ctx, dst, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MinioClientAPI_CopyObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyObject'
type MinioClientAPI_CopyObject_Call struct {
	*mock.Call
}

// CopyObject is a helper method to define mock.On call
//   - ctx context.Context
//   - dst minio.CopyDestOptions
//   - src minio.CopySrcOptions
func (_e *MinioClientAPI_Expecter) CopyObject(ctx interface{}, dst interface{}, src interface{}) *MinioClientAPI_CopyObject_Call {
	return &MinioClientAPI_CopyObject_Call{Call: _e.mock.On("CopyObject", ctx, dst, src)}
}

func (_c *MinioClientAPI_CopyObject_Call) Run(run func(ctx context.Context, dst minio.CopyDestOptions, src minio.CopySrcOptions)) *MinioClientAPI_CopyObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(minio.CopyDestOptions), args[2].(minio.CopySrcOptions))
	})
	return _c
}

func (_c *MinioClientAPI_CopyObject_Call) Return(_a0 minio.UploadInfo, _a1 error) *MinioClientAPI_CopyObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MinioClientAPI_CopyObject_Call) RunAndReturn(run func(context.Context, minio.CopyDestOptions, minio.CopySrcOptions) (minio.UploadInfo, error)) *MinioClientAPI_CopyObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function with given fields: ctx, bucketName, objectName, opts
func (_m *MinioClientAPI) GetObject(ctx context.Context, bucketName string, objectName string, opts minio.GetObjectOptions) (*minio.Object, error) {
	ret := _m.Called(ctx, bucketName, objectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *minio.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, minio.GetObjectOptions) (*minio.Object, error)); ok {
		return rf(ctx, bucketName, objectName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, minio.GetObjectOptions) *minio.Object); ok {
		r0 = rf(ctx, bucketName, objectName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*minio.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, minio.GetObjectOptions) error); ok {
		r1 = rf(ctx, bucketName, objectName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MinioClientAPI_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MinioClientAPI_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - objectName string
//   - opts minio.GetObjectOptions
func (_e *MinioClientAPI_Expecter) GetObject(ctx interface{}, bucketName interface{}, objectName interface{}, opts interface{}) *MinioClientAPI_GetObject_Call {
	return &MinioClientAPI_GetObject_Call{Call: _e.mock.On("GetObject", ctx, bucketName, objectName, opts)}
}

func (_c *MinioClientAPI_GetObject_Call) Run(run func(ctx context.Context, bucketName string, objectName string, opts minio.GetObjectOptions)) *MinioClientAPI_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(minio.GetObjectOptions))
	})
	return _c
}

func (_c *MinioClientAPI_GetObject_Call) Return(_a0 *minio.Object, _a1 error) *MinioClientAPI_GetObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MinioClientAPI_GetObject_Call) RunAndReturn(run func(context.Context, string, string, minio.GetObjectOptions) (*minio.Object, error)) *MinioClientAPI_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function with given fields: ctx, bucketName, opts
func (_m *MinioClientAPI) ListObjects(ctx context.Context, bucketName string, opts minio.ListObjectsOptions) <-chan minio.ObjectInfo {
	ret := _m.Called(ctx, bucketName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 <-chan minio.ObjectInfo
	if rf, ok := ret.Get(0).(func(context.Context, string, minio.ListObjectsOptions) <-chan minio.ObjectInfo); ok {
		r0 = rf(ctx, bucketName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan minio.ObjectInfo)
		}
	}

	return r0
}

// MinioClientAPI_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type MinioClientAPI_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - opts minio.ListObjectsOptions
func (_e *MinioClientAPI_Expecter) ListObjects(ctx interface{}, bucketName interface{}, opts interface{}) *MinioClientAPI_ListObjects_Call {
	return &MinioClientAPI_ListObjects_Call{Call: _e.mock.On("ListObjects", ctx, bucketName, opts)}
}

func (_c *MinioClientAPI_ListObjects_Call) Run(run func(ctx context.Context, bucketName string, opts minio.ListObjectsOptions)) *MinioClientAPI_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(minio.ListObjectsOptions))
	})
	return _c
}

func (_c *MinioClientAPI_ListObjects_Call) Return(_a0 <-chan minio.ObjectInfo) *MinioClientAPI_ListObjects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MinioClientAPI_ListObjects_Call) RunAndReturn(run func(context.Context, string, minio.ListObjectsOptions) <-chan minio.ObjectInfo) *MinioClientAPI_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function with given fields: ctx, bucketName, objectName, reader, objectSize, opts
func (_m *MinioClientAPI) PutObject(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions) (minio.UploadInfo, error) {
	ret := _m.Called(ctx, bucketName, objectName, reader, objectSize, opts)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 minio.UploadInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, int64, minio.PutObjectOptions) (minio.UploadInfo, error)); ok {
		return rf(ctx, bucketName, objectName, reader, objectSize, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, int64, minio.PutObjectOptions) minio.UploadInfo); ok {
		r0 = rf(ctx, bucketName, objectName, reader, objectSize, opts)
	} else {
		r0 = ret.Get(0).(minio.UploadInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, int64, minio.PutObjectOptions) error); ok {
		r1 = rf(ctx, bucketName, objectName, reader, objectSize, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MinioClientAPI_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MinioClientAPI_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - objectName string
//   - reader io.Reader
//   - objectSize int64
//   - opts minio.PutObjectOptions
func (_e *MinioClientAPI_Expecter) PutObject(ctx interface{}, bucketName interface{}, objectName interface{}, reader interface{}, objectSize interface{}, opts interface{}) *MinioClientAPI_PutObject_Call {
	return &MinioClientAPI_PutObject_Call{Call: _e.mock.On("PutObject", ctx, bucketName, objectName, reader, objectSize, opts)}
}

func (_c *MinioClientAPI_PutObject_Call) Run(run func(ctx context.Context, bucketName string, objectName string, reader io.Reader, objectSize int64, opts minio.PutObjectOptions)) *MinioClientAPI_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(io.Reader), args[4].(int64), args[5].(minio.PutObjectOptions))
	})
	return _c
}

func (_c *MinioClientAPI_PutObject_Call) Return(_a0 minio.UploadInfo, _a1 error) *MinioClientAPI_PutObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MinioClientAPI_PutObject_Call) RunAndReturn(run func(context.Context, string, string, io.Reader, int64, minio.PutObjectOptions) (minio.UploadInfo, error)) *MinioClientAPI_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveObject provides a mock function with given fields: ctx, bucketName, objectName, opts
func (_m *MinioClientAPI) RemoveObject(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions) error {
	ret := _m.Called(ctx, bucketName, objectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for RemoveObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, minio.RemoveObjectOptions) error); ok {
		r0 = rf(ctx, bucketName, objectName, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MinioClientAPI_RemoveObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveObject'
type MinioClientAPI_RemoveObject_Call struct {
	*mock.Call
}

// RemoveObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - objectName string
//   - opts minio.RemoveObjectOptions
func (_e *MinioClientAPI_Expecter) RemoveObject(ctx interface{}, bucketName interface{}, objectName interface{}, opts interface{}) *MinioClientAPI_RemoveObject_Call {
	return &MinioClientAPI_RemoveObject_Call{Call: _e.mock.On("RemoveObject", ctx, bucketName, objectName, opts)}
}

func (_c *MinioClientAPI_RemoveObject_Call) Run(run func(ctx context.Context, bucketName string, objectName string, opts minio.RemoveObjectOptions)) *MinioClientAPI_RemoveObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(minio.RemoveObjectOptions))
	})
	return _c
}

func (_c *MinioClientAPI_RemoveObject_Call) Return(_a0 error) *MinioClientAPI_RemoveObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MinioClientAPI_RemoveObject_Call) RunAndReturn(run func(context.Context, string, string, minio.RemoveObjectOptions) error) *MinioClientAPI_RemoveObject_Call {
	_c.Call.Return(run)
	return _c
}

// StatObject provides a mock function with given fields: ctx, bucketName, objectName, opts
func (_m *MinioClientAPI) StatObject(ctx context.Context, bucketName string, objectName string, opts minio.GetObjectOptions) (minio.ObjectInfo, error) {
	ret := _m.Called(ctx, bucketName, objectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for StatObject")
	}

	var r0 minio.ObjectInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, minio.GetObjectOptions) (minio.ObjectInfo, error)); ok {
		return rf(ctx, bucketName, objectName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, minio.GetObjectOptions) minio.ObjectInfo); ok {
		r0 = rf(ctx, bucketName, objectName, opts)
	} else {
		r0 = ret.Get(0).(minio.ObjectInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, minio.GetObjectOptions) error); ok {
		r1 = rf(ctx, bucketName, objectName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MinioClientAPI_StatObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatObject'
type MinioClientAPI_StatObject_Call struct {
	*mock.Call
}

// StatObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - objectName string
//   - opts minio.GetObjectOptions
func (_e *MinioClientAPI_Expecter) StatObject(ctx interface{}, bucketName interface{}, objectName interface{}, opts interface{}) *MinioClientAPI_StatObject_Call {
	return &MinioClientAPI_StatObject_Call{Call: _e.mock.On("StatObject", ctx, bucketName, objectName, opts)}
}

func (_c *MinioClientAPI_StatObject_Call) Run(run func(ctx context.Context, bucketName string, objectName string, opts minio.GetObjectOptions)) *MinioClientAPI_StatObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(minio.GetObjectOptions))
	})
	return _c
}

func (_c *MinioClientAPI_StatObject_Call) Return(_a0 minio.ObjectInfo, _a1 error) *MinioClientAPI_StatObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MinioClientAPI_StatObject_Call) RunAndReturn(run func(context.Context, string, string, minio.GetObjectOptions) (minio.ObjectInfo, error)) *MinioClientAPI_StatObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMinioClientAPI creates a new instance of MinioClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMinioClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MinioClientAPI {
	mock := &MinioClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
