// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks_logstore_client

import (
	context "context"

	client "github.com/zilliztech/woodpecker/woodpecker/client"

	mock "github.com/stretchr/testify/mock"
)

// LogStoreClientPool is an autogenerated mock type for the LogStoreClientPool type
type LogStoreClientPool struct {
	mock.Mock
}

type LogStoreClientPool_Expecter struct {
	mock *mock.Mock
}

func (_m *LogStoreClientPool) EXPECT() *LogStoreClientPool_Expecter {
	return &LogStoreClientPool_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with given fields: ctx, target
func (_m *LogStoreClientPool) Clear(ctx context.Context, target string) {
	_m.Called(ctx, target)
}

// LogStoreClientPool_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type LogStoreClientPool_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *LogStoreClientPool_Expecter) Clear(ctx interface{}, target interface{}) *LogStoreClientPool_Clear_Call {
	return &LogStoreClientPool_Clear_Call{Call: _e.mock.On("Clear", ctx, target)}
}

func (_c *LogStoreClientPool_Clear_Call) Run(run func(ctx context.Context, target string)) *LogStoreClientPool_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LogStoreClientPool_Clear_Call) Return() *LogStoreClientPool_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *LogStoreClientPool_Clear_Call) RunAndReturn(run func(context.Context, string)) *LogStoreClientPool_Clear_Call {
	_c.Run(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *LogStoreClientPool) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogStoreClientPool_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type LogStoreClientPool_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LogStoreClientPool_Expecter) Close(ctx interface{}) *LogStoreClientPool_Close_Call {
	return &LogStoreClientPool_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *LogStoreClientPool_Close_Call) Run(run func(ctx context.Context)) *LogStoreClientPool_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LogStoreClientPool_Close_Call) Return(_a0 error) *LogStoreClientPool_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogStoreClientPool_Close_Call) RunAndReturn(run func(context.Context) error) *LogStoreClientPool_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogStoreClient provides a mock function with given fields: ctx, target
func (_m *LogStoreClientPool) GetLogStoreClient(ctx context.Context, target string) (client.LogStoreClient, error) {
	ret := _m.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for GetLogStoreClient")
	}

	var r0 client.LogStoreClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (client.LogStoreClient, error)); ok {
		return rf(ctx, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) client.LogStoreClient); ok {
		r0 = rf(ctx, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.LogStoreClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogStoreClientPool_GetLogStoreClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogStoreClient'
type LogStoreClientPool_GetLogStoreClient_Call struct {
	*mock.Call
}

// GetLogStoreClient is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *LogStoreClientPool_Expecter) GetLogStoreClient(ctx interface{}, target interface{}) *LogStoreClientPool_GetLogStoreClient_Call {
	return &LogStoreClientPool_GetLogStoreClient_Call{Call: _e.mock.On("GetLogStoreClient", ctx, target)}
}

func (_c *LogStoreClientPool_GetLogStoreClient_Call) Run(run func(ctx context.Context, target string)) *LogStoreClientPool_GetLogStoreClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LogStoreClientPool_GetLogStoreClient_Call) Return(_a0 client.LogStoreClient, _a1 error) *LogStoreClientPool_GetLogStoreClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogStoreClientPool_GetLogStoreClient_Call) RunAndReturn(run func(context.Context, string) (client.LogStoreClient, error)) *LogStoreClientPool_GetLogStoreClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogStoreClientPool creates a new instance of LogStoreClientPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogStoreClientPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogStoreClientPool {
	mock := &LogStoreClientPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
