// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_aliyun

import mock "github.com/stretchr/testify/mock"

// MockCredential is an autogenerated mock type for the Credential type
type MockCredential struct {
	mock.Mock
}

type MockCredential_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredential) EXPECT() *MockCredential_Expecter {
	return &MockCredential_Expecter{mock: &_m.Mock}
}

// GetAccessKeyId provides a mock function with no fields
func (_m *MockCredential) GetAccessKeyId() (*string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccessKeyId")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func() (*string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredential_GetAccessKeyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessKeyId'
type MockCredential_GetAccessKeyId_Call struct {
	*mock.Call
}

// GetAccessKeyId is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetAccessKeyId() *MockCredential_GetAccessKeyId_Call {
	return &MockCredential_GetAccessKeyId_Call{Call: _e.mock.On("GetAccessKeyId")}
}

func (_c *MockCredential_GetAccessKeyId_Call) Run(run func()) *MockCredential_GetAccessKeyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetAccessKeyId_Call) Return(_a0 *string, _a1 error) *MockCredential_GetAccessKeyId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredential_GetAccessKeyId_Call) RunAndReturn(run func() (*string, error)) *MockCredential_GetAccessKeyId_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessKeySecret provides a mock function with no fields
func (_m *MockCredential) GetAccessKeySecret() (*string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccessKeySecret")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func() (*string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredential_GetAccessKeySecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessKeySecret'
type MockCredential_GetAccessKeySecret_Call struct {
	*mock.Call
}

// GetAccessKeySecret is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetAccessKeySecret() *MockCredential_GetAccessKeySecret_Call {
	return &MockCredential_GetAccessKeySecret_Call{Call: _e.mock.On("GetAccessKeySecret")}
}

func (_c *MockCredential_GetAccessKeySecret_Call) Run(run func()) *MockCredential_GetAccessKeySecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetAccessKeySecret_Call) Return(_a0 *string, _a1 error) *MockCredential_GetAccessKeySecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredential_GetAccessKeySecret_Call) RunAndReturn(run func() (*string, error)) *MockCredential_GetAccessKeySecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetBearerToken provides a mock function with no fields
func (_m *MockCredential) GetBearerToken() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBearerToken")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// MockCredential_GetBearerToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBearerToken'
type MockCredential_GetBearerToken_Call struct {
	*mock.Call
}

// GetBearerToken is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetBearerToken() *MockCredential_GetBearerToken_Call {
	return &MockCredential_GetBearerToken_Call{Call: _e.mock.On("GetBearerToken")}
}

func (_c *MockCredential_GetBearerToken_Call) Run(run func()) *MockCredential_GetBearerToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetBearerToken_Call) Return(_a0 *string) *MockCredential_GetBearerToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredential_GetBearerToken_Call) RunAndReturn(run func() *string) *MockCredential_GetBearerToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecurityToken provides a mock function with no fields
func (_m *MockCredential) GetSecurityToken() (*string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSecurityToken")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func() (*string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredential_GetSecurityToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecurityToken'
type MockCredential_GetSecurityToken_Call struct {
	*mock.Call
}

// GetSecurityToken is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetSecurityToken() *MockCredential_GetSecurityToken_Call {
	return &MockCredential_GetSecurityToken_Call{Call: _e.mock.On("GetSecurityToken")}
}

func (_c *MockCredential_GetSecurityToken_Call) Run(run func()) *MockCredential_GetSecurityToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetSecurityToken_Call) Return(_a0 *string, _a1 error) *MockCredential_GetSecurityToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredential_GetSecurityToken_Call) RunAndReturn(run func() (*string, error)) *MockCredential_GetSecurityToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function with no fields
func (_m *MockCredential) GetType() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// MockCredential_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type MockCredential_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetType() *MockCredential_GetType_Call {
	return &MockCredential_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *MockCredential_GetType_Call) Run(run func()) *MockCredential_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetType_Call) Return(_a0 *string) *MockCredential_GetType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredential_GetType_Call) RunAndReturn(run func() *string) *MockCredential_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredential creates a new instance of MockCredential. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredential(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredential {
	mock := &MockCredential{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
