// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks_minio

import mock "github.com/stretchr/testify/mock"

// FileReader is an autogenerated mock type for the FileReader type
type FileReader struct {
	mock.Mock
}

type FileReader_Expecter struct {
	mock *mock.Mock
}

func (_m *FileReader) EXPECT() *FileReader_Expecter {
	return &FileReader_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *FileReader) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type FileReader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *FileReader_Expecter) Close() *FileReader_Close_Call {
	return &FileReader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *FileReader_Close_Call) Run(run func()) *FileReader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileReader_Close_Call) Return(_a0 error) *FileReader_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileReader_Close_Call) RunAndReturn(run func() error) *FileReader_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: p
func (_m *FileReader) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type FileReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *FileReader_Expecter) Read(p interface{}) *FileReader_Read_Call {
	return &FileReader_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *FileReader_Read_Call) Run(run func(p []byte)) *FileReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *FileReader_Read_Call) Return(n int, err error) *FileReader_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *FileReader_Read_Call) RunAndReturn(run func([]byte) (int, error)) *FileReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function with given fields: p, off
func (_m *FileReader) ReadAt(p []byte, off int64) (int, error) {
	ret := _m.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return rf(p, off)
	}
	if rf, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = rf(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = rf(p, off)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileReader_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type FileReader_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *FileReader_Expecter) ReadAt(p interface{}, off interface{}) *FileReader_ReadAt_Call {
	return &FileReader_ReadAt_Call{Call: _e.mock.On("ReadAt", p, off)}
}

func (_c *FileReader_ReadAt_Call) Run(run func(p []byte, off int64)) *FileReader_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(int64))
	})
	return _c
}

func (_c *FileReader_ReadAt_Call) Return(n int, err error) *FileReader_ReadAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *FileReader_ReadAt_Call) RunAndReturn(run func([]byte, int64) (int, error)) *FileReader_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function with given fields: offset, whence
func (_m *FileReader) Seek(offset int64, whence int) (int64, error) {
	ret := _m.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return rf(offset, whence)
	}
	if rf, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = rf(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(offset, whence)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileReader_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type FileReader_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *FileReader_Expecter) Seek(offset interface{}, whence interface{}) *FileReader_Seek_Call {
	return &FileReader_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *FileReader_Seek_Call) Run(run func(offset int64, whence int)) *FileReader_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *FileReader_Seek_Call) Return(_a0 int64, _a1 error) *FileReader_Seek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileReader_Seek_Call) RunAndReturn(run func(int64, int) (int64, error)) *FileReader_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *FileReader) Size() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileReader_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type FileReader_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *FileReader_Expecter) Size() *FileReader_Size_Call {
	return &FileReader_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *FileReader_Size_Call) Run(run func()) *FileReader_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileReader_Size_Call) Return(_a0 int64, _a1 error) *FileReader_Size_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileReader_Size_Call) RunAndReturn(run func() (int64, error)) *FileReader_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileReader creates a new instance of FileReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileReader {
	mock := &FileReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
