// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks_log_handle

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	log "github.com/zilliztech/woodpecker/woodpecker/log"

	proto "github.com/zilliztech/woodpecker/proto"
)

// LogHandle is an autogenerated mock type for the LogHandle type
type LogHandle struct {
	mock.Mock
}

type LogHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *LogHandle) EXPECT() *LogHandle_Expecter {
	return &LogHandle_Expecter{mock: &_m.Mock}
}

// GetLastRecordId provides a mock function with given fields: _a0
func (_m *LogHandle) GetLastRecordId(_a0 context.Context) (*log.LogMessageId, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetLastRecordId")
	}

	var r0 *log.LogMessageId
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*log.LogMessageId, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *log.LogMessageId); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*log.LogMessageId)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogHandle_GetLastRecordId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastRecordId'
type LogHandle_GetLastRecordId_Call struct {
	*mock.Call
}

// GetLastRecordId is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *LogHandle_Expecter) GetLastRecordId(_a0 interface{}) *LogHandle_GetLastRecordId_Call {
	return &LogHandle_GetLastRecordId_Call{Call: _e.mock.On("GetLastRecordId", _a0)}
}

func (_c *LogHandle_GetLastRecordId_Call) Run(run func(_a0 context.Context)) *LogHandle_GetLastRecordId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LogHandle_GetLastRecordId_Call) Return(_a0 *log.LogMessageId, _a1 error) *LogHandle_GetLastRecordId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogHandle_GetLastRecordId_Call) RunAndReturn(run func(context.Context) (*log.LogMessageId, error)) *LogHandle_GetLastRecordId_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with given fields:
func (_m *LogHandle) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LogHandle_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type LogHandle_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *LogHandle_Expecter) GetName() *LogHandle_GetName_Call {
	return &LogHandle_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *LogHandle_GetName_Call) Run(run func()) *LogHandle_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LogHandle_GetName_Call) Return(_a0 string) *LogHandle_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogHandle_GetName_Call) RunAndReturn(run func() string) *LogHandle_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetSegments provides a mock function with given fields: _a0
func (_m *LogHandle) GetSegments(_a0 context.Context) (map[int64]*proto.SegmentMetadata, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetSegments")
	}

	var r0 map[int64]*proto.SegmentMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[int64]*proto.SegmentMetadata, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[int64]*proto.SegmentMetadata); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]*proto.SegmentMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogHandle_GetSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSegments'
type LogHandle_GetSegments_Call struct {
	*mock.Call
}

// GetSegments is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *LogHandle_Expecter) GetSegments(_a0 interface{}) *LogHandle_GetSegments_Call {
	return &LogHandle_GetSegments_Call{Call: _e.mock.On("GetSegments", _a0)}
}

func (_c *LogHandle_GetSegments_Call) Run(run func(_a0 context.Context)) *LogHandle_GetSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LogHandle_GetSegments_Call) Return(_a0 map[int64]*proto.SegmentMetadata, _a1 error) *LogHandle_GetSegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogHandle_GetSegments_Call) RunAndReturn(run func(context.Context) (map[int64]*proto.SegmentMetadata, error)) *LogHandle_GetSegments_Call {
	_c.Call.Return(run)
	return _c
}

// OpenLogReader provides a mock function with given fields: _a0, _a1
func (_m *LogHandle) OpenLogReader(_a0 context.Context, _a1 *log.LogMessageId) (log.LogReader, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for OpenLogReader")
	}

	var r0 log.LogReader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *log.LogMessageId) (log.LogReader, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *log.LogMessageId) log.LogReader); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.LogReader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *log.LogMessageId) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogHandle_OpenLogReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenLogReader'
type LogHandle_OpenLogReader_Call struct {
	*mock.Call
}

// OpenLogReader is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *log.LogMessageId
func (_e *LogHandle_Expecter) OpenLogReader(_a0 interface{}, _a1 interface{}) *LogHandle_OpenLogReader_Call {
	return &LogHandle_OpenLogReader_Call{Call: _e.mock.On("OpenLogReader", _a0, _a1)}
}

func (_c *LogHandle_OpenLogReader_Call) Run(run func(_a0 context.Context, _a1 *log.LogMessageId)) *LogHandle_OpenLogReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*log.LogMessageId))
	})
	return _c
}

func (_c *LogHandle_OpenLogReader_Call) Return(_a0 log.LogReader, _a1 error) *LogHandle_OpenLogReader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogHandle_OpenLogReader_Call) RunAndReturn(run func(context.Context, *log.LogMessageId) (log.LogReader, error)) *LogHandle_OpenLogReader_Call {
	_c.Call.Return(run)
	return _c
}

// OpenLogWriter provides a mock function with given fields: _a0
func (_m *LogHandle) OpenLogWriter(_a0 context.Context) (log.LogWriter, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for OpenLogWriter")
	}

	var r0 log.LogWriter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (log.LogWriter, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) log.LogWriter); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.LogWriter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogHandle_OpenLogWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenLogWriter'
type LogHandle_OpenLogWriter_Call struct {
	*mock.Call
}

// OpenLogWriter is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *LogHandle_Expecter) OpenLogWriter(_a0 interface{}) *LogHandle_OpenLogWriter_Call {
	return &LogHandle_OpenLogWriter_Call{Call: _e.mock.On("OpenLogWriter", _a0)}
}

func (_c *LogHandle_OpenLogWriter_Call) Run(run func(_a0 context.Context)) *LogHandle_OpenLogWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LogHandle_OpenLogWriter_Call) Return(_a0 log.LogWriter, _a1 error) *LogHandle_OpenLogWriter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogHandle_OpenLogWriter_Call) RunAndReturn(run func(context.Context) (log.LogWriter, error)) *LogHandle_OpenLogWriter_Call {
	_c.Call.Return(run)
	return _c
}

// Truncate provides a mock function with given fields: _a0, _a1
func (_m *LogHandle) Truncate(_a0 context.Context, _a1 int64) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Truncate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogHandle_Truncate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Truncate'
type LogHandle_Truncate_Call struct {
	*mock.Call
}

// Truncate is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
func (_e *LogHandle_Expecter) Truncate(_a0 interface{}, _a1 interface{}) *LogHandle_Truncate_Call {
	return &LogHandle_Truncate_Call{Call: _e.mock.On("Truncate", _a0, _a1)}
}

func (_c *LogHandle_Truncate_Call) Run(run func(_a0 context.Context, _a1 int64)) *LogHandle_Truncate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *LogHandle_Truncate_Call) Return(_a0 error) *LogHandle_Truncate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogHandle_Truncate_Call) RunAndReturn(run func(context.Context, int64) error) *LogHandle_Truncate_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogHandle creates a new instance of LogHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogHandle {
	mock := &LogHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
