// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks_storage

import (
	context "context"

	channel "github.com/zilliztech/woodpecker/common/channel"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/zilliztech/woodpecker/server/storage"
)

// Segment is an autogenerated mock type for the Segment type
type Segment struct {
	mock.Mock
}

type Segment_Expecter struct {
	mock *mock.Mock
}

func (_m *Segment) EXPECT() *Segment_Expecter {
	return &Segment_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, data
func (_m *Segment) Append(ctx context.Context, data []byte) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Segment_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type Segment_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *Segment_Expecter) Append(ctx interface{}, data interface{}) *Segment_Append_Call {
	return &Segment_Append_Call{Call: _e.mock.On("Append", ctx, data)}
}

func (_c *Segment_Append_Call) Run(run func(ctx context.Context, data []byte)) *Segment_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *Segment_Append_Call) Return(_a0 error) *Segment_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Segment_Append_Call) RunAndReturn(run func(context.Context, []byte) error) *Segment_Append_Call {
	_c.Call.Return(run)
	return _c
}

// AppendAsync provides a mock function with given fields: ctx, entryId, data, resultCh
func (_m *Segment) AppendAsync(ctx context.Context, entryId int64, data []byte, resultCh channel.ResultChannel) (int64, error) {
	ret := _m.Called(ctx, entryId, data, resultCh)

	if len(ret) == 0 {
		panic("no return value specified for AppendAsync")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []byte, channel.ResultChannel) (int64, error)); ok {
		return rf(ctx, entryId, data, resultCh)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []byte, channel.ResultChannel) int64); ok {
		r0 = rf(ctx, entryId, data, resultCh)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []byte, channel.ResultChannel) error); ok {
		r1 = rf(ctx, entryId, data, resultCh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Segment_AppendAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendAsync'
type Segment_AppendAsync_Call struct {
	*mock.Call
}

// AppendAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - entryId int64
//   - data []byte
//   - resultCh channel.ResultChannel
func (_e *Segment_Expecter) AppendAsync(ctx interface{}, entryId interface{}, data interface{}, resultCh interface{}) *Segment_AppendAsync_Call {
	return &Segment_AppendAsync_Call{Call: _e.mock.On("AppendAsync", ctx, entryId, data, resultCh)}
}

func (_c *Segment_AppendAsync_Call) Run(run func(ctx context.Context, entryId int64, data []byte, resultCh channel.ResultChannel)) *Segment_AppendAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]byte), args[3].(channel.ResultChannel))
	})
	return _c
}

func (_c *Segment_AppendAsync_Call) Return(_a0 int64, _a1 error) *Segment_AppendAsync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Segment_AppendAsync_Call) RunAndReturn(run func(context.Context, int64, []byte, channel.ResultChannel) (int64, error)) *Segment_AppendAsync_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *Segment) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Segment_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Segment_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Segment_Expecter) Close(ctx interface{}) *Segment_Close_Call {
	return &Segment_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *Segment_Close_Call) Run(run func(ctx context.Context)) *Segment_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Segment_Close_Call) Return(_a0 error) *Segment_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Segment_Close_Call) RunAndReturn(run func(context.Context) error) *Segment_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFragments provides a mock function with given fields: ctx, flag
func (_m *Segment) DeleteFragments(ctx context.Context, flag int) error {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFragments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, flag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Segment_DeleteFragments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFragments'
type Segment_DeleteFragments_Call struct {
	*mock.Call
}

// DeleteFragments is a helper method to define mock.On call
//   - ctx context.Context
//   - flag int
func (_e *Segment_Expecter) DeleteFragments(ctx interface{}, flag interface{}) *Segment_DeleteFragments_Call {
	return &Segment_DeleteFragments_Call{Call: _e.mock.On("DeleteFragments", ctx, flag)}
}

func (_c *Segment_DeleteFragments_Call) Run(run func(ctx context.Context, flag int)) *Segment_DeleteFragments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Segment_DeleteFragments_Call) Return(_a0 error) *Segment_DeleteFragments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Segment_DeleteFragments_Call) RunAndReturn(run func(context.Context, int) error) *Segment_DeleteFragments_Call {
	_c.Call.Return(run)
	return _c
}

// Fence provides a mock function with given fields: ctx
func (_m *Segment) Fence(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fence")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Segment_Fence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fence'
type Segment_Fence_Call struct {
	*mock.Call
}

// Fence is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Segment_Expecter) Fence(ctx interface{}) *Segment_Fence_Call {
	return &Segment_Fence_Call{Call: _e.mock.On("Fence", ctx)}
}

func (_c *Segment_Fence_Call) Run(run func(ctx context.Context)) *Segment_Fence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Segment_Fence_Call) Return(_a0 int64, _a1 error) *Segment_Fence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Segment_Fence_Call) RunAndReturn(run func(context.Context) (int64, error)) *Segment_Fence_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function with no fields
func (_m *Segment) GetId() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Segment_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type Segment_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *Segment_Expecter) GetId() *Segment_GetId_Call {
	return &Segment_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *Segment_GetId_Call) Run(run func()) *Segment_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Segment_GetId_Call) Return(_a0 int64) *Segment_GetId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Segment_GetId_Call) RunAndReturn(run func() int64) *Segment_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastEntryId provides a mock function with given fields: ctx
func (_m *Segment) GetLastEntryId(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastEntryId")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Segment_GetLastEntryId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastEntryId'
type Segment_GetLastEntryId_Call struct {
	*mock.Call
}

// GetLastEntryId is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Segment_Expecter) GetLastEntryId(ctx interface{}) *Segment_GetLastEntryId_Call {
	return &Segment_GetLastEntryId_Call{Call: _e.mock.On("GetLastEntryId", ctx)}
}

func (_c *Segment_GetLastEntryId_Call) Run(run func(ctx context.Context)) *Segment_GetLastEntryId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Segment_GetLastEntryId_Call) Return(_a0 int64, _a1 error) *Segment_GetLastEntryId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Segment_GetLastEntryId_Call) RunAndReturn(run func(context.Context) (int64, error)) *Segment_GetLastEntryId_Call {
	_c.Call.Return(run)
	return _c
}

// IsFenced provides a mock function with given fields: ctx
func (_m *Segment) IsFenced(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsFenced")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Segment_IsFenced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFenced'
type Segment_IsFenced_Call struct {
	*mock.Call
}

// IsFenced is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Segment_Expecter) IsFenced(ctx interface{}) *Segment_IsFenced_Call {
	return &Segment_IsFenced_Call{Call: _e.mock.On("IsFenced", ctx)}
}

func (_c *Segment_IsFenced_Call) Run(run func(ctx context.Context)) *Segment_IsFenced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Segment_IsFenced_Call) Return(_a0 bool, _a1 error) *Segment_IsFenced_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Segment_IsFenced_Call) RunAndReturn(run func(context.Context) (bool, error)) *Segment_IsFenced_Call {
	_c.Call.Return(run)
	return _c
}

// LastFragmentId provides a mock function with no fields
func (_m *Segment) LastFragmentId() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastFragmentId")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Segment_LastFragmentId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastFragmentId'
type Segment_LastFragmentId_Call struct {
	*mock.Call
}

// LastFragmentId is a helper method to define mock.On call
func (_e *Segment_Expecter) LastFragmentId() *Segment_LastFragmentId_Call {
	return &Segment_LastFragmentId_Call{Call: _e.mock.On("LastFragmentId")}
}

func (_c *Segment_LastFragmentId_Call) Run(run func()) *Segment_LastFragmentId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Segment_LastFragmentId_Call) Return(_a0 int64) *Segment_LastFragmentId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Segment_LastFragmentId_Call) RunAndReturn(run func() int64) *Segment_LastFragmentId_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: ctx
func (_m *Segment) Load(ctx context.Context) (int64, storage.Fragment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 int64
	var r1 storage.Fragment
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, storage.Fragment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) storage.Fragment); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(storage.Fragment)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Segment_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Segment_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Segment_Expecter) Load(ctx interface{}) *Segment_Load_Call {
	return &Segment_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *Segment_Load_Call) Run(run func(ctx context.Context)) *Segment_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Segment_Load_Call) Return(_a0 int64, _a1 storage.Fragment, _a2 error) *Segment_Load_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Segment_Load_Call) RunAndReturn(run func(context.Context) (int64, storage.Fragment, error)) *Segment_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function with given fields: ctx
func (_m *Segment) Merge(ctx context.Context) ([]storage.Fragment, []int32, []int32, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 []storage.Fragment
	var r1 []int32
	var r2 []int32
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]storage.Fragment, []int32, []int32, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []storage.Fragment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Fragment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []int32); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]int32)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) []int32); ok {
		r2 = rf(ctx)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]int32)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context) error); ok {
		r3 = rf(ctx)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Segment_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type Segment_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Segment_Expecter) Merge(ctx interface{}) *Segment_Merge_Call {
	return &Segment_Merge_Call{Call: _e.mock.On("Merge", ctx)}
}

func (_c *Segment_Merge_Call) Run(run func(ctx context.Context)) *Segment_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Segment_Merge_Call) Return(_a0 []storage.Fragment, _a1 []int32, _a2 []int32, _a3 error) *Segment_Merge_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *Segment_Merge_Call) RunAndReturn(run func(context.Context) ([]storage.Fragment, []int32, []int32, error)) *Segment_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// NewReader provides a mock function with given fields: ctx, opt
func (_m *Segment) NewReader(ctx context.Context, opt storage.ReaderOpt) (storage.Reader, error) {
	ret := _m.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for NewReader")
	}

	var r0 storage.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.ReaderOpt) (storage.Reader, error)); ok {
		return rf(ctx, opt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, storage.ReaderOpt) storage.Reader); ok {
		r0 = rf(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, storage.ReaderOpt) error); ok {
		r1 = rf(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Segment_NewReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewReader'
type Segment_NewReader_Call struct {
	*mock.Call
}

// NewReader is a helper method to define mock.On call
//   - ctx context.Context
//   - opt storage.ReaderOpt
func (_e *Segment_Expecter) NewReader(ctx interface{}, opt interface{}) *Segment_NewReader_Call {
	return &Segment_NewReader_Call{Call: _e.mock.On("NewReader", ctx, opt)}
}

func (_c *Segment_NewReader_Call) Run(run func(ctx context.Context, opt storage.ReaderOpt)) *Segment_NewReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(storage.ReaderOpt))
	})
	return _c
}

func (_c *Segment_NewReader_Call) Return(_a0 storage.Reader, _a1 error) *Segment_NewReader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Segment_NewReader_Call) RunAndReturn(run func(context.Context, storage.ReaderOpt) (storage.Reader, error)) *Segment_NewReader_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function with given fields: ctx
func (_m *Segment) Sync(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Segment_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type Segment_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Segment_Expecter) Sync(ctx interface{}) *Segment_Sync_Call {
	return &Segment_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *Segment_Sync_Call) Run(run func(ctx context.Context)) *Segment_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Segment_Sync_Call) Return(_a0 error) *Segment_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Segment_Sync_Call) RunAndReturn(run func(context.Context) error) *Segment_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewSegment creates a new instance of Segment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSegment(t interface {
	mock.TestingT
	Cleanup(func())
}) *Segment {
	mock := &Segment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
