// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_tencent

import mock "github.com/stretchr/testify/mock"

// MockCredential is an autogenerated mock type for the Credential type
type MockCredential struct {
	mock.Mock
}

type MockCredential_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredential) EXPECT() *MockCredential_Expecter {
	return &MockCredential_Expecter{mock: &_m.Mock}
}

// GetCredential provides a mock function with no fields
func (_m *MockCredential) GetCredential() (string, string, string) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCredential")
	}

	var r0 string
	var r1 string
	var r2 string
	if rf, ok := ret.Get(0).(func() (string, string, string)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func() string); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(string)
	}

	return r0, r1, r2
}

// MockCredential_GetCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredential'
type MockCredential_GetCredential_Call struct {
	*mock.Call
}

// GetCredential is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetCredential() *MockCredential_GetCredential_Call {
	return &MockCredential_GetCredential_Call{Call: _e.mock.On("GetCredential")}
}

func (_c *MockCredential_GetCredential_Call) Run(run func()) *MockCredential_GetCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetCredential_Call) Return(_a0 string, _a1 string, _a2 string) *MockCredential_GetCredential_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCredential_GetCredential_Call) RunAndReturn(run func() (string, string, string)) *MockCredential_GetCredential_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretId provides a mock function with no fields
func (_m *MockCredential) GetSecretId() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSecretId")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCredential_GetSecretId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretId'
type MockCredential_GetSecretId_Call struct {
	*mock.Call
}

// GetSecretId is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetSecretId() *MockCredential_GetSecretId_Call {
	return &MockCredential_GetSecretId_Call{Call: _e.mock.On("GetSecretId")}
}

func (_c *MockCredential_GetSecretId_Call) Run(run func()) *MockCredential_GetSecretId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetSecretId_Call) Return(_a0 string) *MockCredential_GetSecretId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredential_GetSecretId_Call) RunAndReturn(run func() string) *MockCredential_GetSecretId_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretKey provides a mock function with no fields
func (_m *MockCredential) GetSecretKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSecretKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCredential_GetSecretKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretKey'
type MockCredential_GetSecretKey_Call struct {
	*mock.Call
}

// GetSecretKey is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetSecretKey() *MockCredential_GetSecretKey_Call {
	return &MockCredential_GetSecretKey_Call{Call: _e.mock.On("GetSecretKey")}
}

func (_c *MockCredential_GetSecretKey_Call) Run(run func()) *MockCredential_GetSecretKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetSecretKey_Call) Return(_a0 string) *MockCredential_GetSecretKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredential_GetSecretKey_Call) RunAndReturn(run func() string) *MockCredential_GetSecretKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function with no fields
func (_m *MockCredential) GetToken() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCredential_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockCredential_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
func (_e *MockCredential_Expecter) GetToken() *MockCredential_GetToken_Call {
	return &MockCredential_GetToken_Call{Call: _e.mock.On("GetToken")}
}

func (_c *MockCredential_GetToken_Call) Run(run func()) *MockCredential_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredential_GetToken_Call) Return(_a0 string) *MockCredential_GetToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredential_GetToken_Call) RunAndReturn(run func() string) *MockCredential_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredential creates a new instance of MockCredential. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredential(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredential {
	mock := &MockCredential{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
