// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_quorum

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	proto "github.com/zilliztech/woodpecker/proto"
)

// QuorumDiscovery is an autogenerated mock type for the QuorumDiscovery type
type QuorumDiscovery struct {
	mock.Mock
}

type QuorumDiscovery_Expecter struct {
	mock *mock.Mock
}

func (_m *QuorumDiscovery) EXPECT() *QuorumDiscovery_Expecter {
	return &QuorumDiscovery_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *QuorumDiscovery) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QuorumDiscovery_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type QuorumDiscovery_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *QuorumDiscovery_Expecter) Close(ctx interface{}) *QuorumDiscovery_Close_Call {
	return &QuorumDiscovery_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *QuorumDiscovery_Close_Call) Run(run func(ctx context.Context)) *QuorumDiscovery_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *QuorumDiscovery_Close_Call) Return(_a0 error) *QuorumDiscovery_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QuorumDiscovery_Close_Call) RunAndReturn(run func(context.Context) error) *QuorumDiscovery_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SelectQuorum provides a mock function with given fields: ctx
func (_m *QuorumDiscovery) SelectQuorum(ctx context.Context) (*proto.QuorumInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SelectQuorum")
	}

	var r0 *proto.QuorumInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*proto.QuorumInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *proto.QuorumInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.QuorumInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QuorumDiscovery_SelectQuorum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectQuorum'
type QuorumDiscovery_SelectQuorum_Call struct {
	*mock.Call
}

// SelectQuorum is a helper method to define mock.On call
//   - ctx context.Context
func (_e *QuorumDiscovery_Expecter) SelectQuorum(ctx interface{}) *QuorumDiscovery_SelectQuorum_Call {
	return &QuorumDiscovery_SelectQuorum_Call{Call: _e.mock.On("SelectQuorum", ctx)}
}

func (_c *QuorumDiscovery_SelectQuorum_Call) Run(run func(ctx context.Context)) *QuorumDiscovery_SelectQuorum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *QuorumDiscovery_SelectQuorum_Call) Return(_a0 *proto.QuorumInfo, _a1 error) *QuorumDiscovery_SelectQuorum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QuorumDiscovery_SelectQuorum_Call) RunAndReturn(run func(context.Context) (*proto.QuorumInfo, error)) *QuorumDiscovery_SelectQuorum_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuorumDiscovery creates a new instance of QuorumDiscovery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuorumDiscovery(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuorumDiscovery {
	mock := &QuorumDiscovery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
