name: Nightly Integration Tests

on:
  schedule:
    # 16:15 UTC = 00:15 Beijing Time (UTC+8)
    - cron: "15 16 * * *"
    # 18:15 UTC = 02:15 Beijing Time (UTC+8)
    - cron: "15 18 * * *"
    # 20:15 UTC = 04:15 Beijing Time (UTC+8)
    - cron: "15 20 * * *"
  workflow_dispatch:

jobs:
  e2e-local:
    name: E2E Local
    uses: ./.github/workflows/integration-test-e2e-local.yaml
    secrets: inherit

  e2e-objectstorage:
    name: E2E Object Storage
    uses: ./.github/workflows/integration-test-e2e-objectstorage.yaml
    secrets: inherit

  e2e-service:
    name: E2E Service
    uses: ./.github/workflows/integration-test-e2e-service.yaml
    secrets: inherit

  component-test:
    name: Component Integration Test
    uses: ./.github/workflows/integration-test-components.yaml
    secrets: inherit

  chaos-test:
    name: Chaos Test
    uses: ./.github/workflows/integration-test-chaos.yaml
    secrets: inherit
